name: webserver

on: [push]

jobs:
  example-job:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run a one-liner script
      run: echo "Hello, GitHub Actions!"